---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nso-614
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nso-614
    spec:
      containers:
        - name: nso-614
          image: jc3943/nso-sys:6.1.4
          command: ["/bin/bash","-c","/etc/init.d/ncs start && /bin/sleep 3650d"]
          imagePullPolicy: "Always"
---
kind: Service
apiVersion: v1
metadata:
  name: nso-614
  labels:
    app: nso-614
spec:
  selector:
    app: nso-614
  ports:
  - name: nso-614-http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: nso-614-netconf
    protocol: TCP
    port: 2022
    targetPort: 2022
  - name: nso-614-ssh
    protocol: TCP
    port: 2024
    targetPort: 2024
  selector:
    app: nso-614
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster