---
- hosts: localhost
  name: Clone Ubuntu Template
  gather_facts: false
  vars: 
    vcenter_password: 'asdfasdf'

  tasks:
  - read_csv:
    path: vars/jb-hosts.csv
  register: vmlist
  tags: jb

  - name: TASK - Clone Ubuntu Template
    community.vmware.vmware_guest:
      #hostname: '{{ item.vcsaAddress }}'
      hostname: 172.16.10.241
      username: 'administrator@vsphere.local'
      #password: '{{ vcenter_password }}'
      password: DEVP@ssw0rd
      validate_certs: no
      name: '{{ vms.name_prefix }}{{ pod_name }}'
      template: '{{ vms.template }}'
      folder: /
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ cluster_name }}'
      networks:
        - name: CG61|CL-PODS|EPG_POD1
          type: static
          ip: '{{ vms.ip_address }}'
          netmask: '{{ vms.netmask }}'
          gateway: '{{ vms.gateway }}'
          connected: yes
          start_connected: yes
      state: poweredon
    loop: "{{ vmlist.list }}"
    loop_control:
        loop_var: vms
    delegate_to: localhost
