---
- hosts: localhost
  name: Clone Ubuntu Template
  gather_facts: false
  vars: 
    vcenter_password: 'asdfasdf'

  tasks:
  - read_csv:
      path: $varPath/vmware/jb-hosts.csv
    register: vmlist
    tags: jb

  - name: TASK - Clone Ubuntu Template
    community.vmware.vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcsa_user }}'
      password: '{{ vcsa_pw }}'
      validate_certs: no
      template: '{{ vms.template }}'
      #name: '{{ vms.prefix }}{{ pod_name }}'
      name: 'ubuntu-{{ pod_name }}'
      folder: /
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ cluster_name }}'
      customization:
        dns_servers:
        - 172.16.10.100
      networks:
        - name: 'CG61|CL-PODS|EPG_{{ u_branch }}'
          type: static
          ip: '{{ vms.ipAddress }}'
          netmask: '{{ vms.netmask }}'
          gateway: '{{ vms.gateway }}'
          connected: yes
          start_connected: yes
      state: poweredon
    loop: "{{ vmlist.list }}"
    loop_control:
        loop_var: vms
    delegate_to: localhost
