kubectl create serviceaccount jenkins-admin-pod10 -n pod10
kubectl create clusterrolebinding jenkins-admin-pod10 --clusterrole=cluster-admin --serviceaccount=pod10:jenkins-admin-pod10
kubectl create serviceaccount jenkins-admin-pod11 -n pod11
kubectl create clusterrolebinding jenkins-admin-pod11 --clusterrole=cluster-admin --serviceaccount=pod11:jenkins-admin-pod11
kubectl create serviceaccount jenkins-admin-pod12 -n pod12
kubectl create clusterrolebinding jenkins-admin-pod12 --clusterrole=cluster-admin --serviceaccount=pod12:jenkins-admin-pod12
kubectl create serviceaccount jenkins-admin-pod13 -n pod13
kubectl create clusterrolebinding jenkins-admin-pod13 --clusterrole=cluster-admin --serviceaccount=pod13:jenkins-admin-pod13
kubectl create serviceaccount jenkins-admin-pod14 -n pod14
kubectl create clusterrolebinding jenkins-admin-pod14 --clusterrole=cluster-admin --serviceaccount=pod14:jenkins-admin-pod14
kubectl create serviceaccount jenkins-admin-pod15 -n pod15
kubectl create clusterrolebinding jenkins-admin-pod15 --clusterrole=cluster-admin --serviceaccount=pod15:jenkins-admin-pod15
kubectl create serviceaccount jenkins-admin-pod16 -n pod16
kubectl create clusterrolebinding jenkins-admin-pod16 --clusterrole=cluster-admin --serviceaccount=pod16:jenkins-admin-pod16
kubectl create serviceaccount jenkins-admin-pod3 -n pod3
kubectl create clusterrolebinding jenkins-admin-pod3 --clusterrole=cluster-admin --serviceaccount=pod3:jenkins-admin-pod3
kubectl create serviceaccount jenkins-admin-pod4 -n pod4
kubectl create clusterrolebinding jenkins-admin-pod4 --clusterrole=cluster-admin --serviceaccount=pod4:jenkins-admin-pod4
kubectl create serviceaccount jenkins-admin-pod5 -n pod5
kubectl create clusterrolebinding jenkins-admin-pod5 --clusterrole=cluster-admin --serviceaccount=pod5:jenkins-admin-pod5
kubectl create serviceaccount jenkins-admin-pod6 -n pod6
kubectl create clusterrolebinding jenkins-admin-pod6 --clusterrole=cluster-admin --serviceaccount=pod6:jenkins-admin-pod6
kubectl create serviceaccount jenkins-admin-pod7 -n pod7
kubectl create clusterrolebinding jenkins-admin-pod7 --clusterrole=cluster-admin --serviceaccount=pod7:jenkins-admin-pod7
kubectl create serviceaccount jenkins-admin-pod8 -n pod8
kubectl create clusterrolebinding jenkins-admin-pod8 --clusterrole=cluster-admin --serviceaccount=pod8:jenkins-admin-pod8
kubectl create serviceaccount jenkins-admin-pod9 -n pod9
kubectl create clusterrolebinding jenkins-admin-pod9 --clusterrole=cluster-admin --serviceaccount=pod9:jenkins-admin-pod9
